Firebase security
Bostonhacks/cacioepepe pull request #112
Opened 2020-09-18 14:49 UTC by vitorvicente

## Description

Finalized the transition to Firebase rules from Firebase Functions. Added & changed the Firestore Rules, deleted unused Functions, and changed Codebase to directly access the Firestore Database.

## Related Issues

https://github.com/Bostonhacks/cacioepepe/issues/102

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

2020-09-18 14:57 UTC, rishabnayak commented
please resolve conflicts!

2020-09-19 02:45 UTC, vitorvicente commented
@rishabnayak Conflicts solved as of right now (10:45PM)

2020-09-19 03:05 UTC, vitorvicente commented
All done, merging conflicts fixed & production bugs fixed

2020-09-19 03:27 UTC, rishabnayak submitted a review, later dismissed

2020-09-19 03:32 UTC, rishabnayak commented
@vitorvicente we shouldn't install the firebase admin package on the front end either because it won't be able to authenticate. to use array union, use it like this - ```firebase.firestore.FieldValue.arrayUnion()```

additionally, the function deploy script in the readme is actually correct - we have a custom deploy script because we kept hitting deploy limits!

2020-09-19 03:35 UTC, rishabnayak requested changes

2020-09-19 03:35 UTC, rishabnayak commented on README.md
> +firebase deploy --only functions
```suggestion
npm run deploy
```

this actually runs a custom deploy script we wrote!

2020-09-19 03:35 UTC, rishabnayak commented on package.json
> +    "firebase-admin": "^9.2.0",
undo

2020-09-19 13:58 UTC, vitorvicente commented on package.json
> +    "firebase-admin": "^9.2.0",
Resolved

2020-09-19 14:00 UTC, vitorvicente commented
Removed firebase-admin dependency (sorry I didn't see it while I was revising the PR), made arrayUnion and export of /firebase/init.js

2020-09-19 14:42 UTC, rishabnayak approved these changes

2020-09-19 14:43 UTC, rishabnayak commented
LGTM! Thank you so much for getting this done @vitorvicente @jy-clairechoi!

2020-09-19 14:43 UTC, merged